name: Build and Push Java GDAL Docker Image

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      gdal_version:
        description: 'GDAL版本号 (例如: 3.8.5, 3.9.2, 3.10.1, 3.11.3)'
        required: true
        default: '3.8.5'
        type: string
      java_version:
        description: 'Java版本'
        required: true
        default: '8'
        type: choice
        options:
        - '8'
        - '11'
        - '17'
        - '21'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache GDAL source
      uses: actions/cache@v4
      with:
        path: /tmp/gdal-${{ inputs.gdal_version || '3.8.5' }}.tar.gz
        key: gdal-source-${{ inputs.gdal_version || '3.8.5' }}-${{ github.sha }}
        restore-keys: |
          gdal-source-${{ inputs.gdal_version || '3.8.5' }}-

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (amd64)
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          freelabspace/java-gdal:java${{ inputs.java_version || '8' }}-gdal${{ inputs.gdal_version || '3.8.5' }}-amd64
          freelabspace/java-gdal:latest-amd64
        build-args: |
          GDAL_VERSION=${{ inputs.gdal_version || '3.8.5' }}
          JAVA_VERSION=${{ inputs.java_version || '8' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-latest
    needs: build-amd64  # arm64 依赖 amd64 完成，避免资源竞争
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache GDAL source
      uses: actions/cache@v4
      with:
        path: /tmp/gdal-${{ inputs.gdal_version || '3.8.5' }}.tar.gz
        key: gdal-source-${{ inputs.gdal_version || '3.8.5' }}-${{ github.sha }}
        restore-keys: |
          gdal-source-${{ inputs.gdal_version || '3.8.5' }}-

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (arm64)
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          freelabspace/java-gdal:java${{ inputs.java_version || '8' }}-gdal${{ inputs.gdal_version || '3.8.5' }}-arm64
          freelabspace/java-gdal:latest-arm64
        build-args: |
          GDAL_VERSION=${{ inputs.gdal_version || '3.8.5' }}
          JAVA_VERSION=${{ inputs.java_version || '8' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    if: github.event_name != 'pull_request'
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create and push manifest
      run: |
        docker manifest create freelabspace/java-gdal:java${{ inputs.java_version || '8' }}-gdal${{ inputs.gdal_version || '3.8.5' }} \
          --amend freelabspace/java-gdal:java${{ inputs.java_version || '8' }}-gdal${{ inputs.gdal_version || '3.8.5' }}-amd64 \
          --amend freelabspace/java-gdal:java${{ inputs.java_version || '8' }}-gdal${{ inputs.gdal_version || '3.